---
title: "PE_MEEDE_COMP_2020_ONLY"
author: "Shane Weisberg"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
#knitr::opts_chunk$set(echo = TRUE)

library(knitr)
#library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
knitr::opts_chunk$set(error = FALSE)

wd = getwd()
setwd('C:/Users/sweisberg/OneDrive - Research Triangle Institute/Documents/EMA/EMA/Model/Results')

source("process_PE_results.R")

# options
PLANT_TYPES = c("slr", "ngcc", "ngtb", "wnd", "col", "bio", "hyd","nuc")
REGION_OPTION = "SAGE" # "EMA","SAGE","USA","STATE"

# Organize data and plots
PE_data = combined_df
MEEDE_data = MEEDE_df

ylim_gen = 400
ylim_cap = 75
ylim_wholesale = 100
ylim_cost = 9000
grid_plot = FALSE
if (REGION_OPTION == "SAGE") {
  MEEDE_data = sage_region_rollup(MEEDE_data, region_map)
  PE_data = sage_region_rollup(PE_data, region_map)
  
  ylim_gen = 1250
  ylim_cap = 200
  ylim_cost = 20000
  grid_plot = TRUE
} else if (REGION_OPTION == "USA") {
  MEEDE_data = usa_region_rollup(MEEDE_data)
  PE_data = usa_region_rollup(PE_data)
  
  ylim_gen = 2250
  ylim_cap = 400
  ylim_cost = 55000
} else if (REGION_OPTION == "STATE") {
  MEEDE_data = MEEDE_df_STATE
  colnames(MEEDE_data)[1] = "region"
  PE_data = combined_df_STATE
  
  ylim_gen = 1000
  ylim_cap = 200
  ylim_cost = 25000
}

REGIONS = unique(PE_data$region)

```

## Total Regional Capacity

```{r capacity, echo=FALSE, warning = FALSE, message = FALSE}
#ALL_IN_ONE = FALSE

if (grid_plot) {
  p = NA
for (r in REGIONS) {
    p_ = comparison_bargraphs(MEEDE_data, PE_data, y_var = "capacity", region = r, 
                              plant_type_filter = PLANT_TYPES, ylim = ylim_cap, grid = grid_plot)
    
    if (is.na(p)) {
      p = p_
    } else {
      p = p + p_
    }
  }
  p = p + plot_layout(guides = "collect") + plot_annotation(title = "MEEDE/PE Comparison: Capacity (GW), SAGE Regions")
  
} else {
  for (r in REGIONS) {
    p = comparison_bargraphs(MEEDE_data, PE_data, y_var = "capacity", region = r, 
                              plant_type_filter = PLANT_TYPES, ylim = ylim_cap, grid = grid_plot)
    print(p)
  }
}
#print(p)
```

## Total Regional Generation

```{r generation, echo=FALSE, warning = FALSE, message = FALSE}
#ALL_IN_ONE = FALSE

if (grid_plot) {
  p = NA
  for (r in REGIONS) {
      p_ = comparison_bargraphs(MEEDE_data, PE_data, y_var = "generation", region = r, 
                                plant_type_filter = PLANT_TYPES, ylim = ylim_gen, grid = grid_plot)
      
      if (is.na(p)) {
        p = p_
      } else {
        p = p + p_
      }
    }
    p = p + plot_layout(guides = "collect") + plot_annotation(title = "MEEDE/PE Comparison: Generation (TWh), SAGE Regions")
  
} else {
  for (r in REGIONS) {
    p = comparison_bargraphs(MEEDE_data, PE_data, y_var = "generation", region = r, 
                              plant_type_filter = PLANT_TYPES, ylim = ylim_gen, grid = grid_plot)
    print(p)
  }
}
print(p)


```


## Average Wholesale Price

```{r wholesale, echo=FALSE, warning = FALSE, message = FALSE}
#ALL_IN_ONE = FALSE

if (grid_plot) {
  p = NA
  for (r in REGIONS) {
      p_ = comparison_bargraph_wholesale(MEEDE_data, PE_data, region = r, 
                                plant_type_filter = PLANT_TYPES, ylim = ylim_wholesale, grid = grid_plot)
      
      if (is.na(p)) {
        p = p_
      } else {
        p = p + p_
      }
    }
    p = p + plot_layout(guides = "collect") + plot_annotation(title = "MEEDE/PE Comparison: Wholesale price ($/MWh), SAGE Regions")
  
} else {
  for (r in REGIONS) {
    p = comparison_bargraph_wholesale(MEEDE_data, PE_data, region = r, 
                              plant_type_filter = PLANT_TYPES, ylim = ylim_wholesale, grid = grid_plot)
    print(p)
  }
}
print(p)


```

## Total Regional Costs

```{r total_cost, echo=FALSE, warning = FALSE, message = FALSE}
#ALL_IN_ONE = FALSE

#for (r in REGIONS) {
#  p = comparison_bargraphs(MEEDE_data, PE_data, y_var = "total_cost", region = r, plant_type_filter = #PLANT_TYPES, ylim = ylim_cost)
  
  #print(p)
#}


```

## Total Regional Fixed Costs

```{r fixed_cost, echo=FALSE, warning = FALSE, message = FALSE}
#ALL_IN_ONE = FALSE

# for (r in REGIONS) {
#   p = comparison_bargraphs(MEEDE_data, PE_data, y_var = "fixed_cost", region = r, plant_type_filter = PLANT_TYPES, ylim = 6000)
#   
#   print(p)
# }


```

## Total Regional Variable Costs

```{r var_cost, echo=FALSE, warning = FALSE, message = FALSE}
#ALL_IN_ONE = FALSE

# for (r in REGIONS) {
#   p = comparison_bargraphs(MEEDE_data, PE_data, y_var = "variable_cost", region = r, plant_type_filter = PLANT_TYPES, ylim = 4000)
#   
#   print(p)
# }


```